#pragma once

#include <string>

namespace MegaManLofi
{
   class ArenaGenerationDefs
   {
   public:
      // 's': solid, blocks in all directions
      // 'p': platform, only blocks downward
      static std::string GetArenaTilesString()
      {
         std::string tiles =
            "                                                                                                                                                                                                                                                                                                                                         sssssssssssssssssssssssssssssss" \
            "                                                                                                                                                                                                                                                                                                                                         s                              " \
            "                                                                                                                                                                                                                                                                                                                                         s                              " \
            "                                                                                                                                                                                                                                                                                                                                         s                              " \
            "                                                                                                                                                                                                                                                                                                                                         s                              " \
            "                                                                                                                                                                                                                                                                                                                                         s              ssssssssssssssss" \
            "                                                                                                                                                                                                                                                                                                                                         s                             s" \
            "                                                                                                                                                                                                                                                                                                                                         s                             s" \
            "                                                                                                                                                                                                                                                                                                                                         s                             s" \
            "ssssssssssssssssssssssssssssss                                                                                                                                                                                                                                                                                                           s                             s" \
            "s                                                                                                                                                                                                                                                                                                                                        sssssssssssssssssss           s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                     ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss" \
            "s                                          sssssssssssssss                                                                                                                                                                                                                                                                                                             s" \
            "s                                                                                                                                                                                                                                                        pppppppppppppppppppppp                                                                                        s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                            pppppppppppppppppppppppppppppppppppppppppp                                                                                                                                                                                s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s    sssssssssssssssssssssssssssss                                                          pppppppppppppppppppppppppppppppppppp                                                                                                                                                                                                                                       s" \
            "s                                                                                                                                                                                                      pppppppppppppppppppppppppppppppppppppppppppppppppppppp                                                                                                          s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                           sssssss                                                                                                                                                                                                                                                                                    s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                            sssssssssssssssss              ssssssssss                                                                                                                                                                                                                                                                                                 s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                           sssssssssssssssssssssssssssssssssssssssssssss                                                                                                                                                                              s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                          pppppppppppppppppppppppppppppp                                                                                                                                                                                                                                                              s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                               ssss                                                   s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                               sssssssssssssssssssssssssss                                                                                                                                                                                                            s" \
            "s                                                           sssssssssssssssssss                                                                                                                                                                                                                                                                                        s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "sppppppppppppppppppppppppppppppppppp                                                                                                                                                                                                                                                                                                                                   s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                  ssss                                s" \
            "s                                                                                  pppppppppppppppppppppppppppppppppp                                                                                                                                                                                                                                                  s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "spppppppp                                                                                                                                                                                                                                                                                                                                                              s" \
            "s                                                                                                                                                                                                                                                                                                        ssss                                                          s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "s                                                                                                                                                                                                                                                                                                                                                                      s" \
            "ssssssssssssssssssssssssssssssssssssssssss                                  sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss                   sssssssssssssssssssssssssssssssssssssssssss                                                                                            s";

         return tiles;
      }
   };
}
