#pragma once

#include <string>

namespace MegaManLofi
{
   class ArenaGenerationStrings
   {
   public:
      // 's': solid, blocks in all directions
      // 'p': platform, only blocks downward
      // 'x': spikes, only blocks upward
      static std::string GetArenaTilesString( int arenaId )
      {
         switch ( arenaId )
         {
            case 0: // 360 x 60
               return
                  "                                                                                                                                                                                                                                                                                                                                         sssssssssssssssssssssssssssssss" \
                  "                                                                                                                                                                                                                                                                                                                                         s                              " \
                  "                                                                                                                                                                                                                                                                                                                                         s                              " \
                  "                                                                                                                                                                                                                                                                                                                                         s                              " \
                  "                                                                                                                                                                                                                                                                                                                                         s                              " \
                  "                                                                                                                                                                                                                                                                                                                                         s              ssssssssssssssss" \
                  "                                                                                                                                                                                                                                                                                                                                         s                             s" \
                  "                                                                                                                                                                                                                                                                                                                                         s                             s" \
                  "                                                                                                                                                                                                                                                                                                                                         s                             s" \
                  "ssssssssssssssssssssssssssssss                                                                                                                                                                                                                                                                                                           s                             s" \
                  "s                                                                                                                                                                                                                                                                                                                                        sssssssssssssssssss           s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                     ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss" \
                  "s                                          sssssssssssssss                                                                                                                                                                                                                                                                                                             s" \
                  "s                                                                                                                                                                                                                                                        ssssssssssssssssssssss                                                                                        s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                            ssssssssssssssssssssssssssssssssssssssssss                                                                                                                                                                                s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s    sssssssssssssssssssssssssssss                                                          ssssssssssssssssssssssssssssssssssss                                                                                                                                                                                                                                       s" \
                  "s                                                                                                                                                                                                      ssssssssssssssssssssssssssssssssssssssssss                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                            sssssssssssssssss              ssssssssssssss                                                                                                                                                                                                                                                                                             s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                           ssssssssssssxxxxxxxxxxxxxxxxxssssssssssssssss                                                                                                                                                                              s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                 pppppppppppssssssssssss                                                                                                                                                                                                                                                              s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                               ssss                                                   s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                               sssssssssssssssssssssssssss                                                                                                                                                                                                            s" \
                  "s                                                           sssssxxxxxsssssssss                                                                                                                                                                                                                                                                                        s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "spppppppppppppssssssssssssssssssssss                                                                                                                                                                                                                                                                                                                                   s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                  ssss                                s" \
                  "s                                                                                  pppppppppppppppppppppppppppppppppp                                                                                                                                                                                                                                                  s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "sssssssss                                                                                                                                                                                                                                                                                                                                                              s" \
                  "s                                                                                                                                                                                                                                                                                                        ssss                                                          s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "s                                                                                                                                                                                                                                                                                                                                                                      s" \
                  "ssssssssssssssssssssssssssssssssssssssssss                                  sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss                   sssssssssssssssssssssssssssssssssssssssssss                                                                                            s";
            case 1: // 120 x 28
               return
                  "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                    sssssssssssss                                                                                     s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s     ssssss                                                                                                           s" \
                  "s                                            sssssssssssssssssssssssss                                                 s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                ss                                    s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "sssssssssssssssss                                                                                                      s" \
                  "                                                                                                                       s" \
                  "                                                                                                                       s" \
                  "                                                                                              ss                       s" \
                  "                                                                                                                       s" \
                  "ssssssssssssssssssssssss                                                                                               s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                             ssss     s" \
                  "s                                                                                                                      s" \
                  "sssssssssssssssssssssssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            case 2: // 120 x 60
               return
                  "sssssssss                                  sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                   sssssssssssssssssssss                                                                              s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                 ppp          ppp     s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                    ppp                               s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                        ppppppppppppppppppppsssssssssssssssssssssssssss                                               s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                sssssssssssssssssssssssssssssssssssssss                                               s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                   pppppppppppppp             ppppppppppppp                                                           s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s                                                                                                                      s" \
                  "s        xxx           xx           xxxxxx                     xx      x               xxxx          x              xxxs";
            default:
               return "";
         }
      }
   };
}
